### ISSUE TITLE
Missing license for code

### ISSUE THREAD

**Issue by mastricker** [catalyticmaterials/cheat#1]
Hi,
I want to explore the usage of your code and possibly adapt it to a related use case. However, you have not added a license under which conditions it is allowed to use and reuse your data and code. Can you please add a license to your code?

Best wishes,
Markus

**Comment by cmclausen** [comment]
Hi Markus,
Sorry for not noticing this earlier. This repo has been somewhat neglected for an extended period.
An MIT license has been added now. There's also several new updates to this repo on the way. Stay tuned :)
Best regards
Christian
